from model.path import Path

# path1 = Path("testing", 10, 10)
# path1.make_empty_path()
# path1.set_start(1, 1)
# path1.add_next_step(1, 2)
# path1.add_next_step(1, 3)
# path1.draw_path()
# path1.add_next_step(0, 3)
# path1.draw_path()
# path1.add_next_step(-1, 3)
# path1.draw_path()
# path1.add_next_step(0, 4)
# path1.draw_path()
# path1.remove_step()
# path1.draw_path()
# path1.remove_step()
# path1.draw_path()
# path1.remove_step()
# path1.draw_path()
# path1.remove_step()
# path1.draw_path()
# path1.remove_step()
# path1.draw_path()
# path1.set_start(0, 0)
# path1.draw_path()
# print(path1.start_location.x)
# print(path1.start_location.y)
# path1.add_next_step(0, 1)
# path1.add_next_step(0, 2)
# path1.add_next_step(0, 3)
# path1.add_next_step(0, 4)
# path1.add_next_step(0, 5)
# path1.add_next_step(0, 6)
# path1.add_next_step(0, 7)
# path1.add_next_step(0, 8)
# path1.set_end(0, 9)
# path1.draw_path()
# path1.save_path("test")

path2 = Path("testing", 0, 0)
path2.recreate_path_from_file("test")
path2.draw_path()